# Generated by Django 5.2.15 on 2026-07-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thread_pitch',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
