# Generated by Django 5.2.15 on 2026-08-21 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_populate_product_types_and_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='standard',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='ProductLength',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('product_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lengths', to='products.productsize')),
            ],
            options={
                'verbose_name': 'Product Length',
                'verbose_name_plural': 'Product Lengths',
                'ordering': ['name'],
                'unique_together': {('product_size', 'name')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_length',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.productlength'),
        ),
    ]
