# Generated by Django 5.2.15 on 2026-08-23 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='business_description',
            field=models.CharField(blank=True, default='OF HIGH TENSILE FASTENERS', max_length=250),
        ),
        migrations.AddField(
            model_name='company',
            name='business_type',
            field=models.CharField(blank=True, default='STOCKIST | SUPPLIER | EXPORTER', max_length=200),
        ),
        migrations.AddField(
            model_name='company',
            name='tagline',
            field=models.CharField(blank=True, default='FASTENING SYSTEMS', max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, help_text='Comapany logo/ branding image', null=True, upload_to='company/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(help_text='Company Name, e.g. FARENI', max_length=200),
        ),
    ]
