# Generated by Django 5.2.15 on 2026-08-25 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventorytransaction_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransaction',
            name='stock_after_transaction',
            field=models.IntegerField(default=0),
        ),
    ]
